/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      get_game: {
        player1: string;
        player2: string;
        [k: string]: unknown;
      };
    }
  | {
      get_games: {
        [k: string]: unknown;
      };
    }
  | {
      get_games_by_host: {
        host: string;
        [k: string]: unknown;
      };
    }
  | {
      get_games_by_opponent: {
        opponent: string;
        [k: string]: unknown;
      };
    }
  | {
      admin: {
        [k: string]: unknown;
      };
    };
